### ISSUE TITLE
Remove unnecessary comments and empty lines

### ISSUE THREAD

**Issue by ovidiuenache** [marceldobrica/training#19]
Please remove all the unnecessary comments and empty lines from both the src/, tests/, and config/ folders.

**Comment by ovidiuenache** [comment]
In the config/ folder you have all the default instructions from all the packages. Please those comments and leave only the configuration.

**Comment by marceldobrica** [comment]
I think I have removed unnecessary comments from src/ and tests/ folder.
Regarding empty lines.... I have left some for readability.... 
config folder - noted for future.
